extended request output
nikitanovosibirsk/hiphip pull request #1
Opened 2018-11-20 03:29 UTC by ko10ok

2018-11-21 07:21 UTC, tsv1 requested changes

2018-11-21 07:21 UTC, tsv1 commented on hiphip/http/response.py
> +        if request_content_type.startswith("text/") or request_content_type.endswith("/text"):
Разве кто-то отправляет заголовки с `endswith("/text")`?

2018-11-21 07:21 UTC, tsv1 commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
`indent=4` - сейчас так носят)

2018-11-21 07:21 UTC, tsv1 commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
\+ эта строчка должна быть в `else`

2018-11-21 07:22 UTC, ko10ok commented on hiphip/http/response.py
> +        if request_content_type.startswith("text/") or request_content_type.endswith("/text"):
копипаста с нижнего куска кода.

2018-11-21 07:23 UTC, ko10ok commented on hiphip/http/response.py
> +        if request_content_type.startswith("text/") or request_content_type.endswith("/text"):
могу в обоих убрать)

2018-11-21 07:24 UTC, ko10ok commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
Копипаста с нижнего
она в elif.
Добавить в обоих случаях else после elif?

2018-11-21 07:33 UTC, ko10ok commented on hiphip/http/response.py
> +        if request_content_type.startswith("text/") or request_content_type.endswith("/text"):
поправил

2018-11-21 07:33 UTC, ko10ok commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
проправил

2018-11-21 11:41 UTC, nikitanovosibirsk commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
Не, имел в виду `try-except-else`, так как строчку в `json.dumps` не имеет смысла пихать

2018-11-22 03:25 UTC, ko10ok commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
добавил else

2018-11-22 03:25 UTC, ko10ok commented on hiphip/http/response.py
> +            r += json.dumps(request_text, sort_keys=True, ensure_ascii=False, indent=2)
вынес общий кусок для headers-body

2018-11-22 03:33 UTC, merged